# Generated by Django 6.0.3 on 2026-03-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='wilaya',
            field=models.CharField(default='Tlemcen', max_length=100),
        ),
    ]
