# Generated by Django 6.0.3 on 2026-03-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, default='Aucune description disponible.', null=True),
        ),
    ]
