# Generated by Django 5.2.12 on 2026-03-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wilaya', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='restaurants/')),
                ('google_maps_link', models.URLField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
