# Generated by Django 6.0.3 on 2026-03-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('fastfood', 'Fast Food')], default='restaurant', max_length=20),
            preserve_default=False,
        ),
    ]
