# Generated by Django 6.0.3 on 2026-03-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('fastfood', 'Fast Food')], default='restaurant', max_length=20),
        ),
    ]
