# Generated by Django 6.0.3 on 2026-03-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='price',
        ),
    ]
