# Generated by Django 6.0.3 on 2026-03-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_restaurant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.CharField(choices=[('restaurants', 'Restaurants'), ('fastfood', 'Fast Food')], default='restaurants', max_length=20),
        ),
    ]
