# Generated by Django 6.0.3 on 2026-03-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_restaurant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.CharField(choices=[('restaurant', 'Restaurants'), ('fastfood', 'Fast Food')], default='restaurants', max_length=20),
        ),
    ]
